### ISSUE TITLE
Scroll notes on display as they are played

### ISSUE THREAD

**Issue by uiri** [TrebleTrouble/trebletrouble#35]
Depends on #31

**Comment by uiri** [comment]
Should we punt this to next semester and use wrap around instead?

**Comment by Ecobbold** [comment]
- [ ]  Fix Clear Notes
- [ ]  Figure out Screen Bounds (based on time sig) 
- [ ] Draw from arbitrary bar

**Comment by uiri** [comment]
:tada:
