### ISSUE TITLE
3D print case/stand for LCD, BBB & the other peripherals.

### ISSUE THREAD

**Issue by uiri** [TrebleTrouble/trebletrouble#49]
I think Émilie is supposed to do this at some point.
Feel free to re-assign to someone else @Ecobbold 

- [x] 3D Print stand
- [x] Obtain screws
- [x] [stress](https://en.wikipedia.org/wiki/Stress_(mechanics)) test like Real Engineers :tm:

**Comment by Ecobbold** [comment]
Just don't push the legs the wrong way, and we're good to go!
