### ISSUE TITLE
Generate a pitch using the ALSA framework

### ISSUE THREAD

**Issue by tchin018** [TrebleTrouble/trebletrouble#9]
- [x] Recognize speaker on dev machine
- [x] Get sound playing on dev machine
- [x] Recognize speaker on beaglebone
- [x] Get sound playing on beaglebone

**Comment by uiri** [comment]
- [ ] Recognize speaker on dev machine
- [ ] Get sound playing on dev machine
- [ ] Recognize speaker on beaglebone
- [ ] Get sound playing on beaglebone

**Comment by uiri** [comment]
Blocked by #52

**Comment by uiri** [comment]
Does #58 close this? What still has to be done?

**Comment by uiri** [comment]
What exactly is the status on this? (herp derp @tchin018 why you ignore me)
