### ISSUE TITLE
Documentation and Presentation for Winter Midterm

### ISSUE THREAD

**Issue by Ecobbold** [TrebleTrouble/trebletrouble#90]
The follow are tasks that need to be preformed and their due dates fro the Winter Midterm:
- [x] Create Winter Midterm WBS with colours (green, yellow, white) See our Project tab for more info. **(Tejan)** 
- [x] Create Presentation for Wednesday March 1's μ presentation **(Tejan)**
- [x] Create Presentation for Winter Midterm based off Fall Final **(Emilie)**
- [x] Create the Google Doc Draft **(Emilie)**
- [x] Review the Report **(ALL)**
- [ ] Transfer the reviewed  **(Emilie)**

~Write your part for the report in the Google Doc Drive (Written by Sunday 29th 11:59pm)~
~- [ ] Emilie~
~- [ ] Will~
~- [ ] Daniel~
~- [ ] Tejan~

**Comment by uiri** [comment]
lolsubmitted
